version: '3'
services:
  app:
    build: .
    stdin_open: true
    ports:
    - "8000:8000"
    entrypoint: bash -c "cd blog && yarn install && yarn develop"
    volumes:
    - ".:/usr/src/app"
  bash:
    build: .
    ports:
    - "8000:8000"
    stdin_open: true
    entrypoint: /bin/bash
    volumes:
    - ".:/usr/src/app"
  prod_build:
    build: .
    entrypoint: bash -c "cd blog && yarn build"
    environment: 
      CI: "false"
    volumes:
    - "./docker/build:/usr/src/app/blog/public"